'''
Modify the starter code below to create your own cool drawing
and then Pull Request it to your instructor. Make sure you
keep the last two lines of code. Your first and last name must be written on your art.
The last line keeps the window open until you click to close.

Turtle Documentation: https://docs.python.org/3.3/library/turtle.html?highlight=turtle

'''
import turtle
ye=turtle.Turtle()
ye.color('black')
ye.shape('turtle')
ye.speed(10)
ye.width(15)
ye.pu()
ye.goto(0,-150)
ye.pd()
ye.circle(120)
ye.pu()
ye.color('grey')
ye.right(90)
ye.forward(10)
ye.pd()
ye.left(90)
ye.forward(130)
ye.left(90)
ye.forward(260)
ye.left(90)
ye.forward(300)
ye.left(90)
ye.forward(260)
ye.left(90)
ye.forward(170)
ye.pu()
ye.left(180)
ye.forward(130)
ye.right(90)
ye.pd()
ye.forward(260)
ye.pu()
ye.goto(20,-30)
ye.color('black')
ye.pd()
ye.circle(20)
ye.pu()
ye.right(90)
ye.forward(120)
ye.left(90)
ye.forward(40)
ye.pd()
ye.pencolor('red')
ye.color('red')
ye.begin_fill()
ye.left(90)
ye.forward(80)
ye.left(90)
ye.forward(80)
ye.left(90)
ye.forward(80)
ye.left(90)
ye.forward(80)
ye.end_fill()
ye.pu()
ye.goto(150,-165)
ye.hideturtle()
ye.write('Will Fuchs',font=("Arial", 24, "normal"))
turtle.exitonclick()
